services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_TOKEN: ${JWT_REFRESH_SECRET}
      REDIS_URL: ${REDIS_URL}
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      WSS_PORT: ${WSS_PORT}
      MQTT_PORT: ${MQTT_PORT}
      SESSION_SECRET: ${SESSION_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CLOUD_NAME: ${CLOUD_NAME}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo
      - redis
    networks:
      - my_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: smart-home
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network 

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

  ngrok:
    image: ngrok/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    command: http app:${PORT} --url=strong-complete-sculpin.ngrok-free.app
    networks:
      - my_network

volumes:
  mongo_data:
  redis_data:

networks:
  my_network:
    driver: bridge
