services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin@123
      MYSQL_DB: smart_home
      MONGODB_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_TOKEN: ${JWT_REFRESH_SECRET}
      REDIS_HOST: redis
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mysql
      - mongo
      - redis
    networks:
      - my_network  # Tham gia vào mạng tùy chỉnh

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: smart_home
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network  # Tham gia vào mạng tùy chỉnh

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: smarthome
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network  # Tham gia vào mạng tùy chỉnh

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network  # Tham gia vào mạng tùy chỉnh

  # ngrok:
  #   image: ngrok/ngrok
  #   environment:
  #     NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
  #     NGROK_PORT: "${PORT}"
  #   ports:
  #     - "4040:4040"
  #   command: http app:${PORT}
  #   networks:
  #     - my_network  # Tham gia vào mạng tùy chỉnh

volumes:
  mysql_data:
  mongo_data:
  redis_data:

networks:
  my_network:
    driver: bridge  # Sử dụng driver bridge cho mạng
